In [19]:
import pandas as pd
from common import utils

In [20]:
df = pd.read_parquet(utils.find_project_root() / "data" / "raw" / "stage1.parquet")

In [21]:
df

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,awards_and_nominations,cast,box_office,aspect_ratio,countries,languages,production_companies,release_date,comentarios_ia,ai_summary
0,1. Once Upon a Time... in Hollywood,https://www.imdb.com/title/tt7131622/?ref_=sr_t_1,84,R,2019,2h 41m,7.6,(930K),As Hollywood's Golden Age is winding down duri...,[Quentin Tarantino],...,146 wins & 377 nominations total,"[Leonardo DiCaprio, Brad Pitt, Margot Robbie, ...","{'Budget': '$90,000,000 (estimated)', 'Gross U...",2.39 : 1,"[United States, United Kingdom, China]","[English, Italian, Spanish, German]","[Columbia Pictures, Bona Film Group, Heyday Fi...","July 26, 2019 (United States)","[Authentic emotion positive sentiment, Charact...",Reviewers say 'Once Upon a Time in Hollywood' ...
1,2. Mission: Impossible - Dead Reckoning Part One,https://www.imdb.com/title/tt9603212/?ref_=sr_t_2,81,PG-13,2023,2h 43m,7.6,(313K),Ethan Hunt and his IMF team must track down a ...,[Christopher McQuarrie],...,18 wins & 68 nominations total,"[Tom Cruise, Hayley Atwell, Ving Rhames, Simon...","{'Budget': '$291,000,000 (estimated)', 'Gross ...",2.39 : 1,[United States],"[English, Italian, Russian, French]","[Paramount Pictures, Skydance Media, TC Produc...","July 12, 2023 (United States)","[Action sequences positive sentiment, Sound de...",Reviewers say 'Mission: Impossible - Dead Reck...
2,3. John Wick: Chapter 4,https://www.imdb.com/title/tt10366206/?ref_=sr...,78,R,2023,2h 49m,7.6,(394K),John Wick uncovers a path to defeating The Hig...,[Chad Stahelski],...,38 wins & 51 nominations total,"[Keanu Reeves, Laurence Fishburne, George Geor...","{'Budget': '$100,000,000 (estimated)', 'Gross ...",2.39 : 1,"[United States, Germany]","[English, Japanese, Russian, French, Spanish, ...","[Lionsgate, Thunder Road Pictures, 87Eleven En...","March 24, 2023 (United States)","[Action sequences positive sentiment, Cinemato...",Reviewers say 'John Wick: Chapter 4' is lauded...
3,4. The Fifth Element,https://www.imdb.com/title/tt0119116/?ref_=sr_t_4,52,PG-13,1997,2h 6m,7.6,(534K),"In the colorful future, cabdriver Korben Dalla...",[Luc Besson],...,10 wins & 39 nominations total,"[Bruce Willis, Milla Jovovich, Gary Oldman, Ia...","{'Budget': 'FRF 75,210,000 (estimated)', 'Gros...",2.39 : 1,"[France, United Kingdom]","[English, Swedish, German, Arabic, Egyptian (A...","[Gaumont, Pinewood Studios]","May 9, 1997 (United States)",[],
4,5. Watchmen,https://www.imdb.com/title/tt0409459/?ref_=sr_t_5,56,R,2009,2h 42m,7.6,(604K),"In a version of 1985 where superheroes exist, ...",[Zack Snyder],...,12 wins & 24 nominations total,"[Jackie Earle Haley, Patrick Wilson, Carla Gug...","{'Budget': '$130,000,000 (estimated)', 'Gross ...",2.39 : 1,[United States],[English],"[Warner Bros., Paramount Pictures, Legendary E...","March 6, 2009 (United States)","[Ambitious positive sentiment, Cinematography ...",Reviewers say 'Watchmen' is acclaimed for its ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96. Naked,https://www.imdb.com/title/tt0107653/?ref_=sr_...,85,Not Rated,1993,2h 11m,7.7,(48K),An unemployed Mancunian vents his rage on unsu...,[Mike Leigh],...,8 wins & 7 nominations total,"[David Thewlis, Lesley Sharp, Katrin Cartlidge...","{'Budget': None, 'Gross US & Canada': '$1,769,...",1.66 : 1,[United Kingdom],"[English, French]","[Thin Man Films, British Screen Productions, C...","February 4, 1994 (United States)",[],
96,97. Donnie Brasco,https://www.imdb.com/title/tt0119008/?ref_=sr_...,77,R,1997,2h 7m,7.7,(349K),An FBI undercover agent infiltrates the mob an...,[Mike Newell],...,2 wins & 16 nominations total,"[Al Pacino, Johnny Depp, Michael Madsen, Bruno...","{'Budget': '$35,000,000 (estimated)', 'Gross U...",2.39 : 1,[United States],"[English, Italian, Japanese]","[Mandalay Entertainment, Baltimore Pictures, M...","February 28, 1997 (United States)",[],
97,98. Sound of Metal,https://www.imdb.com/title/tt5363618/?ref_=sr_...,82,R,2019,2h,7.7,(163K),"During a series of adrenaline-fueled gigs, iti...",[Darius Marder],...,90 wins & 179 nominations total,"[Riz Ahmed, Olivia Cooke, Paul Raci, Lauren Ri...","{'Budget': '$5,400,000 (estimated)', 'Gross US...",2.39 : 1,[United States],"[English, American Sign Language, French, Pers...","[Caviar, Flat 7 Productions, Ward Four]","December 4, 2020 (United States)",[],
98,99. Sense and Sensibility,https://www.imdb.com/title/tt0114388/?ref_=sr_...,84,PG,1995,2h 16m,7.7,(134K),"In Georgian era England, wealthy Mr. Dashwood ...",[Ang Lee],...,33 wins & 50 nominations total,"[Emma Thompson, Kate Winslet, James Fleet, Tom...","{'Budget': '$16,000,000 (estimated)', 'Gross U...",1.85 : 1,"[United Kingdom, United States]","[English, French]","[Columbia Pictures, Mirage Enterprises]","January 26, 1996 (United States)",[],
99,100. Detachment,https://www.imdb.com/title/tt1683526/?ref_=sr_...,52,Not Rated,2011,1h 38m,7.7,(108K),A substitute teacher who drifts from classroom...,[Tony Kaye],...,8 wins & 4 nominations total,"[Adrien Brody, Christina Hendricks, Marcia Gay...","{'Budget': None, 'Gross US & Canada': '$72,689...",1.85 : 1,[United States],[English],"[Paper Street Films, Appian Way, Kingsgate Films]","February 1, 2012 (France)",[],

In [22]:
df["title"] = df["title"].replace("^[^.]+. ", "", regex=True)
df.head()

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,awards_and_nominations,cast,box_office,aspect_ratio,countries,languages,production_companies,release_date,comentarios_ia,ai_summary
0,Once Upon a Time... in Hollywood,https://www.imdb.com/title/tt7131622/?ref_=sr_t_1,84,R,2019,2h 41m,7.6,(930K),As Hollywood's Golden Age is winding down duri...,[Quentin Tarantino],...,146 wins & 377 nominations total,"[Leonardo DiCaprio, Brad Pitt, Margot Robbie, ...","{'Budget': '$90,000,000 (estimated)', 'Gross U...",2.39 : 1,"[United States, United Kingdom, China]","[English, Italian, Spanish, German]","[Columbia Pictures, Bona Film Group, Heyday Fi...","July 26, 2019 (United States)","[Authentic emotion positive sentiment, Charact...",Reviewers say 'Once Upon a Time in Hollywood' ...
1,Mission: Impossible - Dead Reckoning Part One,https://www.imdb.com/title/tt9603212/?ref_=sr_t_2,81,PG-13,2023,2h 43m,7.6,(313K),Ethan Hunt and his IMF team must track down a ...,[Christopher McQuarrie],...,18 wins & 68 nominations total,"[Tom Cruise, Hayley Atwell, Ving Rhames, Simon...","{'Budget': '$291,000,000 (estimated)', 'Gross ...",2.39 : 1,[United States],"[English, Italian, Russian, French]","[Paramount Pictures, Skydance Media, TC Produc...","July 12, 2023 (United States)","[Action sequences positive sentiment, Sound de...",Reviewers say 'Mission: Impossible - Dead Reck...
2,John Wick: Chapter 4,https://www.imdb.com/title/tt10366206/?ref_=sr...,78,R,2023,2h 49m,7.6,(394K),John Wick uncovers a path to defeating The Hig...,[Chad Stahelski],...,38 wins & 51 nominations total,"[Keanu Reeves, Laurence Fishburne, George Geor...","{'Budget': '$100,000,000 (estimated)', 'Gross ...",2.39 : 1,"[United States, Germany]","[English, Japanese, Russian, French, Spanish, ...","[Lionsgate, Thunder Road Pictures, 87Eleven En...","March 24, 2023 (United States)","[Action sequences positive sentiment, Cinemato...",Reviewers say 'John Wick: Chapter 4' is lauded...
3,The Fifth Element,https://www.imdb.com/title/tt0119116/?ref_=sr_t_4,52,PG-13,1997,2h 6m,7.6,(534K),"In the colorful future, cabdriver Korben Dalla...",[Luc Besson],...,10 wins & 39 nominations total,"[Bruce Willis, Milla Jovovich, Gary Oldman, Ia...","{'Budget': 'FRF 75,210,000 (estimated)', 'Gros...",2.39 : 1,"[France, United Kingdom]","[English, Swedish, German, Arabic, Egyptian (A...","[Gaumont, Pinewood Studios]","May 9, 1997 (United States)",[],
4,Watchmen,https://www.imdb.com/title/tt0409459/?ref_=sr_t_5,56,R,2009,2h 42m,7.6,(604K),"In a version of 1985 where superheroes exist, ...",[Zack Snyder],...,12 wins & 24 nominations total,"[Jackie Earle Haley, Patrick Wilson, Carla Gug...","{'Budget': '$130,000,000 (estimated)', 'Gross ...",2.39 : 1,[United States],[English],"[Warner Bros., Paramount Pictures, Legendary E...","March 6, 2009 (United States)","[Ambitious positive sentiment, Cinematography ...",Reviewers say 'Watchmen' is acclaimed for its ...

In [23]:
def parse_duration(value: str) -> int:
    mins = 0
    for component in value.split(" "):
        if component.endswith("h"):
            hours = int(component[:-1])
            mins += hours * 60
        elif component.endswith("m"):
            minutes = int(component[:-1])
            mins += minutes

    return mins


df["duration_mins"] = df["duration"].apply(parse_duration)
df.head()

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,cast,box_office,aspect_ratio,countries,languages,production_companies,release_date,comentarios_ia,ai_summary,duration_mins
0,Once Upon a Time... in Hollywood,https://www.imdb.com/title/tt7131622/?ref_=sr_t_1,84,R,2019,2h 41m,7.6,(930K),As Hollywood's Golden Age is winding down duri...,[Quentin Tarantino],...,"[Leonardo DiCaprio, Brad Pitt, Margot Robbie, ...","{'Budget': '$90,000,000 (estimated)', 'Gross U...",2.39 : 1,"[United States, United Kingdom, China]","[English, Italian, Spanish, German]","[Columbia Pictures, Bona Film Group, Heyday Fi...","July 26, 2019 (United States)","[Authentic emotion positive sentiment, Charact...",Reviewers say 'Once Upon a Time in Hollywood' ...,161
1,Mission: Impossible - Dead Reckoning Part One,https://www.imdb.com/title/tt9603212/?ref_=sr_t_2,81,PG-13,2023,2h 43m,7.6,(313K),Ethan Hunt and his IMF team must track down a ...,[Christopher McQuarrie],...,"[Tom Cruise, Hayley Atwell, Ving Rhames, Simon...","{'Budget': '$291,000,000 (estimated)', 'Gross ...",2.39 : 1,[United States],"[English, Italian, Russian, French]","[Paramount Pictures, Skydance Media, TC Produc...","July 12, 2023 (United States)","[Action sequences positive sentiment, Sound de...",Reviewers say 'Mission: Impossible - Dead Reck...,163
2,John Wick: Chapter 4,https://www.imdb.com/title/tt10366206/?ref_=sr...,78,R,2023,2h 49m,7.6,(394K),John Wick uncovers a path to defeating The Hig...,[Chad Stahelski],...,"[Keanu Reeves, Laurence Fishburne, George Geor...","{'Budget': '$100,000,000 (estimated)', 'Gross ...",2.39 : 1,"[United States, Germany]","[English, Japanese, Russian, French, Spanish, ...","[Lionsgate, Thunder Road Pictures, 87Eleven En...","March 24, 2023 (United States)","[Action sequences positive sentiment, Cinemato...",Reviewers say 'John Wick: Chapter 4' is lauded...,169
3,The Fifth Element,https://www.imdb.com/title/tt0119116/?ref_=sr_t_4,52,PG-13,1997,2h 6m,7.6,(534K),"In the colorful future, cabdriver Korben Dalla...",[Luc Besson],...,"[Bruce Willis, Milla Jovovich, Gary Oldman, Ia...","{'Budget': 'FRF 75,210,000 (estimated)', 'Gros...",2.39 : 1,"[France, United Kingdom]","[English, Swedish, German, Arabic, Egyptian (A...","[Gaumont, Pinewood Studios]","May 9, 1997 (United States)",[],,126
4,Watchmen,https://www.imdb.com/title/tt0409459/?ref_=sr_t_5,56,R,2009,2h 42m,7.6,(604K),"In a version of 1985 where superheroes exist, ...",[Zack Snyder],...,"[Jackie Earle Haley, Patrick Wilson, Carla Gug...","{'Budget': '$130,000,000 (estimated)', 'Gross ...",2.39 : 1,[United States],[English],"[Warner Bros., Paramount Pictures, Legendary E...","March 6, 2009 (United States)","[Ambitious positive sentiment, Cinematography ...",Reviewers say 'Watchmen' is acclaimed for its ...,162

In [24]:
df["budget"] = df["box_office"].map(lambda x: x.get("Budget", 0))
df["gross_world"] = df["box_office"].map(lambda x: x.get("Gross worldwide", 0))
df["gross_usa_canada"] = df["box_office"].map(lambda x: x.get("Gross US & Canada", 0))
df["opening_weekend_usa_canada"] = df["box_office"].map(lambda x: x.get("Opening weekend US & Canada", None))

df

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,languages,production_companies,release_date,comentarios_ia,ai_summary,duration_mins,budget,gross_world,gross_usa_canada,opening_weekend_usa_canada
0,Once Upon a Time... in Hollywood,https://www.imdb.com/title/tt7131622/?ref_=sr_t_1,84,R,2019,2h 41m,7.6,(930K),As Hollywood's Golden Age is winding down duri...,[Quentin Tarantino],...,"[English, Italian, Spanish, German]","[Columbia Pictures, Bona Film Group, Heyday Fi...","July 26, 2019 (United States)","[Authentic emotion positive sentiment, Charact...",Reviewers say 'Once Upon a Time in Hollywood' ...,161,"$90,000,000 (estimated)","$392,105,159","$142,502,728","$41,082,018Jul 28, 2019"
1,Mission: Impossible - Dead Reckoning Part One,https://www.imdb.com/title/tt9603212/?ref_=sr_t_2,81,PG-13,2023,2h 43m,7.6,(313K),Ethan Hunt and his IMF team must track down a ...,[Christopher McQuarrie],...,"[English, Italian, Russian, French]","[Paramount Pictures, Skydance Media, TC Produc...","July 12, 2023 (United States)","[Action sequences positive sentiment, Sound de...",Reviewers say 'Mission: Impossible - Dead Reck...,163,"$291,000,000 (estimated)","$571,125,435","$172,640,980","$54,688,347Jul 16, 2023"
2,John Wick: Chapter 4,https://www.imdb.com/title/tt10366206/?ref_=sr...,78,R,2023,2h 49m,7.6,(394K),John Wick uncovers a path to defeating The Hig...,[Chad Stahelski],...,"[English, Japanese, Russian, French, Spanish, ...","[Lionsgate, Thunder Road Pictures, 87Eleven En...","March 24, 2023 (United States)","[Action sequences positive sentiment, Cinemato...",Reviewers say 'John Wick: Chapter 4' is lauded...,169,"$100,000,000 (estimated)","$447,142,521","$187,131,806","$73,817,950Mar 26, 2023"
3,The Fifth Element,https://www.imdb.com/title/tt0119116/?ref_=sr_t_4,52,PG-13,1997,2h 6m,7.6,(534K),"In the colorful future, cabdriver Korben Dalla...",[Luc Besson],...,"[English, Swedish, German, Arabic, Egyptian (A...","[Gaumont, Pinewood Studios]","May 9, 1997 (United States)",[],,126,"FRF 75,210,000 (estimated)","$263,920,180","$63,820,180","$17,031,345May 11, 1997"
4,Watchmen,https://www.imdb.com/title/tt0409459/?ref_=sr_t_5,56,R,2009,2h 42m,7.6,(604K),"In a version of 1985 where superheroes exist, ...",[Zack Snyder],...,[English],"[Warner Bros., Paramount Pictures, Legendary E...","March 6, 2009 (United States)","[Ambitious positive sentiment, Cinematography ...",Reviewers say 'Watchmen' is acclaimed for its ...,162,"$130,000,000 (estimated)","$185,382,813","$107,509,799","$55,214,334Mar 8, 2009"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Naked,https://www.imdb.com/title/tt0107653/?ref_=sr_...,85,Not Rated,1993,2h 11m,7.7,(48K),An unemployed Mancunian vents his rage on unsu...,[Mike Leigh],...,"[English, French]","[Thin Man Films, British Screen Productions, C...","February 4, 1994 (United States)",[],,131,None,"$1,797,195","$1,769,305","$36,463Dec 19, 1993"
96,Donnie Brasco,https://www.imdb.com/title/tt0119008/?ref_=sr_...,77,R,1997,2h 7m,7.7,(349K),An FBI undercover agent infiltrates the mob an...,[Mike Newell],...,"[English, Italian, Japanese]","[Mandalay Entertainment, Baltimore Pictures, M...","February 28, 1997 (United States)",[],,127,"$35,000,000 (estimated)","$124,909,762","$41,909,762","$11,660,216Mar 2, 1997"
97,Sound of Metal,https://www.imdb.com/title/tt5363618/?ref_=sr_...,82,R,2019,2h,7.7,(163K),"During a series of adrenaline-fueled gigs, iti...",[Darius Marder],...,"[English, American Sign Language, French, Pers...","[Caviar, Flat 7 Productions, Ward Four]","December 4, 2020 (United States)",[],,120,"$5,400,000 (estimated)","$516,520",None,None
98,Sense and Sensibility,https://www.imdb.com/title/tt0114388/?ref_=sr_...,84,PG,1995,2h 16m,7.7,(134K),"In Georgian era England, wealthy Mr. Dashwood ...",[Ang Lee],...,"[English, French]","[Columbia Pictures, Mirage Enterprises]","January 26, 1996 (United States)",[],,136,"$16,000,000 (estimated)","$134,582,776","$43,182,776","$721,341Dec 17, 1995"
99,Detachment,https://www.imdb.com/title/tt1683526/?ref_=sr_...,52,Not Rated,2011,1h 38m,7.7,(108K),A substitute teacher who drifts from classroom...,[Tony Kaye],...,[English],"[Paper Street Films, Appian Way, Kingsgate Films]","February 1, 2012 (France)",[],,98,None,"$1,688,710","$72,689","$10,739Mar 18, 2012"

In [25]:
import re

def parse_money(value: str) -> float:
    if value is None:
        return None

    value = value.rstrip(" (estimated)")
    value = re.sub(r",", "", value)

    if value.startswith("$"):
        return float(value[1:])
    if value.startswith("FRF"):
        return float(value[4:]) * 0.17871603 # https://www.xe.com/currencyconverter/convert/?Amount=1&From=FRF&To=USD
    if value.startswith("€"):
        return float(value[1:]) * 1.1722995
    if value.startswith("DEM"):
        return float(value[4:]) * 0.59939338
    else:
        return None

def get_faltantes(cdf, original, target):
    return cdf[cdf[target].isna() & ~(cdf[original].isna())]

df["budget_usd"] = df["budget"].map(parse_money)
get_faltantes(df, "budget", "budget_usd")

Empty DataFrame
Columns: [title, url, metacritic_score, rating, year, duration, rating_stars, voters, description, director, writers, stars, storyline, genres, genres_ext, awards_and_nominations, cast, box_office, aspect_ratio, countries, languages, production_companies, release_date, comentarios_ia, ai_summary, duration_mins, budget, gross_world, gross_usa_canada, opening_weekend_usa_canada, budget_usd]
Index: []

[0 rows x 31 columns]

In [26]:
df["gross_world_usd"] = df["gross_world"].map(parse_money)
get_faltantes(df, "gross_world", "gross_world_usd")

Empty DataFrame
Columns: [title, url, metacritic_score, rating, year, duration, rating_stars, voters, description, director, writers, stars, storyline, genres, genres_ext, awards_and_nominations, cast, box_office, aspect_ratio, countries, languages, production_companies, release_date, comentarios_ia, ai_summary, duration_mins, budget, gross_world, gross_usa_canada, opening_weekend_usa_canada, budget_usd, gross_world_usd]
Index: []

[0 rows x 32 columns]

In [27]:
df["gross_usa_canada_usd"] = df["gross_usa_canada"].map(parse_money)
get_faltantes(df, "gross_usa_canada", "gross_usa_canada_usd")

Empty DataFrame
Columns: [title, url, metacritic_score, rating, year, duration, rating_stars, voters, description, director, writers, stars, storyline, genres, genres_ext, awards_and_nominations, cast, box_office, aspect_ratio, countries, languages, production_companies, release_date, comentarios_ia, ai_summary, duration_mins, budget, gross_world, gross_usa_canada, opening_weekend_usa_canada, budget_usd, gross_world_usd, gross_usa_canada_usd]
Index: []

[0 rows x 33 columns]

In [28]:
def split_at_date(value: str) -> (str, str):
    idx = 0

    if value is None:
        return (None, None)

    while idx < len(value):
        try:
            if value[idx].isupper() and value[idx-1].isnumeric():
                return value[:idx], value[idx:]
        except IndexError:
            return value[:idx], value[idx:]

        idx += 1

# df["opening_weekend_usa_canada_usd"] = df["opening_weekend_usa_canada"].map(parse_money)
# get_faltantes(df, "opening_weekend_usa_canada", "opening_weekend_usa_canada_usd")

open_info = df["opening_weekend_usa_canada"].map(split_at_date)
df["opening_weekend_usa_canada_date"] = open_info.map(lambda x: x[1])
df["opening_weekend_usa_canada_usd"] = open_info.map(lambda x: parse_money(x[0]))

get_faltantes(df, "opening_weekend_usa_canada", "opening_weekend_usa_canada_usd")

Empty DataFrame
Columns: [title, url, metacritic_score, rating, year, duration, rating_stars, voters, description, director, writers, stars, storyline, genres, genres_ext, awards_and_nominations, cast, box_office, aspect_ratio, countries, languages, production_companies, release_date, comentarios_ia, ai_summary, duration_mins, budget, gross_world, gross_usa_canada, opening_weekend_usa_canada, budget_usd, gross_world_usd, gross_usa_canada_usd, opening_weekend_usa_canada_date, opening_weekend_usa_canada_usd]
Index: []

[0 rows x 35 columns]

In [29]:
df.head()

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,duration_mins,budget,gross_world,gross_usa_canada,opening_weekend_usa_canada,budget_usd,gross_world_usd,gross_usa_canada_usd,opening_weekend_usa_canada_date,opening_weekend_usa_canada_usd
0,Once Upon a Time... in Hollywood,https://www.imdb.com/title/tt7131622/?ref_=sr_t_1,84,R,2019,2h 41m,7.6,(930K),As Hollywood's Golden Age is winding down duri...,[Quentin Tarantino],...,161,"$90,000,000 (estimated)","$392,105,159","$142,502,728","$41,082,018Jul 28, 2019",9.000000e+07,392105159.0,142502728.0,"Jul 28, 2019",41082018.0
1,Mission: Impossible - Dead Reckoning Part One,https://www.imdb.com/title/tt9603212/?ref_=sr_t_2,81,PG-13,2023,2h 43m,7.6,(313K),Ethan Hunt and his IMF team must track down a ...,[Christopher McQuarrie],...,163,"$291,000,000 (estimated)","$571,125,435","$172,640,980","$54,688,347Jul 16, 2023",2.910000e+08,571125435.0,172640980.0,"Jul 16, 2023",54688347.0
2,John Wick: Chapter 4,https://www.imdb.com/title/tt10366206/?ref_=sr...,78,R,2023,2h 49m,7.6,(394K),John Wick uncovers a path to defeating The Hig...,[Chad Stahelski],...,169,"$100,000,000 (estimated)","$447,142,521","$187,131,806","$73,817,950Mar 26, 2023",1.000000e+08,447142521.0,187131806.0,"Mar 26, 2023",73817950.0
3,The Fifth Element,https://www.imdb.com/title/tt0119116/?ref_=sr_t_4,52,PG-13,1997,2h 6m,7.6,(534K),"In the colorful future, cabdriver Korben Dalla...",[Luc Besson],...,126,"FRF 75,210,000 (estimated)","$263,920,180","$63,820,180","$17,031,345May 11, 1997",1.344123e+07,263920180.0,63820180.0,"May 11, 1997",17031345.0
4,Watchmen,https://www.imdb.com/title/tt0409459/?ref_=sr_t_5,56,R,2009,2h 42m,7.6,(604K),"In a version of 1985 where superheroes exist, ...",[Zack Snyder],...,162,"$130,000,000 (estimated)","$185,382,813","$107,509,799","$55,214,334Mar 8, 2009",1.300000e+08,185382813.0,107509799.0,"Mar 8, 2009",55214334.0

In [30]:
def parse_awards(value: str) -> (int, int):
    words = value.split(" ")
    nominations = 0
    awards = 0

    for idx, word in enumerate(words):
        if word.startswith("win"):
            awards = int(words[idx-1])
        elif word.startswith("nomina"):
            nominations = int(words[idx-1])

    return awards, nominations

df["awards"] = df["awards_and_nominations"].map(lambda x: parse_awards(x)[0])
df["nominations"] = df["awards_and_nominations"].map(lambda x: parse_awards(x)[1])

df[["awards_and_nominations", "awards", "nominations"]].head()

             awards_and_nominations  awards  nominations
0  146 wins & 377 nominations total     146          377
1    18 wins & 68 nominations total      18           68
2    38 wins & 51 nominations total      38           51
3    10 wins & 39 nominations total      10           39
4    12 wins & 24 nominations total      12           24

In [31]:
df["voters_int"] = df["voters"].replace(r"\(|\)| ", "", regex=True).replace("K", "000", regex=True).replace("M", "000000", regex=True).astype("int")

df[["voters", "voters_int"]].head()

    voters  voters_int
0   (930K)      930000
1   (313K)      313000
2   (394K)      394000
3   (534K)      534000
4   (604K)      604000

In [32]:
df["rating_stars_int"] = df["rating_stars"].astype("float")
df[["rating_stars", "rating_stars_int"]].head()

  rating_stars  rating_stars_int
0          7.6               7.6
1          7.6               7.6
2          7.6               7.6
3          7.6               7.6
4          7.6               7.6

In [33]:
df.to_parquet(utils.find_project_root() / "data" / "raw" / "stage2.parquet")