In [16]:
import pandas as pd
from common import utils

In [17]:
df = pd.read_parquet(utils.find_project_root() / "data" / "raw" / "stage1_2.parquet")

In [18]:
df

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,awards_and_nominations,cast,box_office,aspect_ratio,countries,languages,production_companies,release_date,comentarios_ia,ai_summary
0,1. Once Upon a Time... in Hollywood,https://www.imdb.com/title/tt7131622/?ref_=sr_t_1,84,R,2019,2h 41m,7.6,(930K),As Hollywood's Golden Age is winding down duri...,[Quentin Tarantino],...,146 wins & 377 nominations total,"[Leonardo DiCaprio, Brad Pitt, Margot Robbie, ...","{'Budget': '$90,000,000 (estimated)', 'Gross U...",2.39 : 1,"[United States, United Kingdom, China]","[English, Italian, Spanish, German]","[Columbia Pictures, Bona Film Group, Heyday Fi...","July 26, 2019 (United States)","[Authentic emotion positive sentiment, Charact...",Reviewers say 'Once Upon a Time in Hollywood' ...
1,2. Mission: Impossible - Dead Reckoning Part One,https://www.imdb.com/title/tt9603212/?ref_=sr_t_2,81,PG-13,2023,2h 43m,7.6,(313K),Ethan Hunt and his IMF team must track down a ...,[Christopher McQuarrie],...,18 wins & 68 nominations total,"[Tom Cruise, Hayley Atwell, Ving Rhames, Simon...","{'Budget': '$291,000,000 (estimated)', 'Gross ...",2.39 : 1,[United States],"[English, Italian, Russian, French]","[Paramount Pictures, Skydance Media, TC Produc...","July 12, 2023 (United States)","[Action sequences positive sentiment, Sound de...",Reviewers say 'Mission: Impossible - Dead Reck...
2,3. John Wick: Chapter 4,https://www.imdb.com/title/tt10366206/?ref_=sr...,78,R,2023,2h 49m,7.6,(394K),John Wick uncovers a path to defeating The Hig...,[Chad Stahelski],...,38 wins & 51 nominations total,"[Keanu Reeves, Laurence Fishburne, George Geor...","{'Budget': '$100,000,000 (estimated)', 'Gross ...",2.39 : 1,"[United States, Germany]","[English, Japanese, Russian, French, Spanish, ...","[Lionsgate, Thunder Road Pictures, 87Eleven En...","March 24, 2023 (United States)","[Action sequences positive sentiment, Cinemato...",Reviewers say 'John Wick: Chapter 4' is lauded...
3,4. The Fifth Element,https://www.imdb.com/title/tt0119116/?ref_=sr_t_4,52,PG-13,1997,2h 6m,7.6,(534K),"In the colorful future, cabdriver Korben Dalla...",[Luc Besson],...,10 wins & 39 nominations total,"[Bruce Willis, Milla Jovovich, Gary Oldman, Ia...","{'Budget': 'FRF 75,210,000 (estimated)', 'Gros...",2.39 : 1,"[France, United Kingdom]","[English, Swedish, German, Arabic, Egyptian (A...","[Gaumont, Pinewood Studios]","May 9, 1997 (United States)",[],
4,5. Watchmen,https://www.imdb.com/title/tt0409459/?ref_=sr_t_5,56,R,2009,2h 42m,7.6,(604K),"In a version of 1985 where superheroes exist, ...",[Zack Snyder],...,12 wins & 24 nominations total,"[Jackie Earle Haley, Patrick Wilson, Carla Gug...","{'Budget': '$130,000,000 (estimated)', 'Gross ...",2.39 : 1,[United States],[English],"[Warner Bros., Paramount Pictures, Legendary E...","March 6, 2009 (United States)","[Ambitious positive sentiment, Cinematography ...",Reviewers say 'Watchmen' is acclaimed for its ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,66. Home Alone,https://www.imdb.com/title/tt0099785/?ref_=sr_...,63,PG,1990,1h 43m,7.7,(707K),"An eight-year-old troublemaker, mistakenly lef...",[Chris Columbus],...,12 wins & 7 nominations total,"[Macaulay Culkin, Joe Pesci, Daniel Stern, Joh...","{'Budget': '$18,000,000 (estimated)', 'Gross U...",,[United States],"[English, French]","[Twentieth Century Fox, Hughes Entertainment]","November 16, 1990 (United States)",[],
66,67. Blue Velvet,https://www.imdb.com/title/tt0090756/?ref_=sr_...,75,R,1986,2h,7.7,(237K),The discovery of a severed human ear found in ...,[David Lynch],...,18 wins & 18 nominations total,"[Isabella Rossellini, Kyle MacLachlan, Dennis ...","{'Budget': '$6,000,000 (estimated)', 'Gross US...",2.35 : 1,[United States],[English],[De Laurentiis Entertainment Group (DEG)],"October 23, 1986 (Italy)",[],
67,68. When Harry Met Sally...,https://www.imdb.com/title/tt0098635/?ref_=sr_...,76,R,1989,1h 35m,7.7,(260K),Harry and Sally have known each other for year...,[Rob Reiner],...,6 wins & 19 nominations total,"[Billy Crystal, Meg Ryan, Carrie Fisher, Bruno...","{'Budget': '$16,000,000 (estimated)', 'Gross U...",1.85 : 1,[United States],[English],"[Castle Rock Entertainment, Nelson Entertainme...","July 21, 1989 (United States)",[],
68,"69. O Brother, Where Art Thou?",https://www.imdb.com/title/tt0190590/?ref_=sr_...,69,PG-13,2000,1h 47m,7.7,(345K),"In the deep south during the 1930s, three esca...","[Joel Coen, Ethan Coen]",...,8 wins & 38 nominations total,"[George Clooney, John Turturro, Tim Blake Nels...","{'Budget': '$26,000,000 (estimated)', 'Gross U...",2.39 : 1,"[United Kingdom, France, United States]",[English],"[Touchstone Pictures, Universal Pictures, Stud...","February 2, 2001 (United States)",[],
69,70. A Few Good Men,https://www.imdb.com/title/tt0104257/?ref_=sr_...,62,R,1992,2h 18m,7.7,(308K),A military lawyer intends to prove that two US...,[Rob Reiner],...,10 wins & 30 nominations total,"[Tom Cruise, Jack Nicholson, Demi Moore, Kevin...","{'Budget': '$41,000,000 (estimated)', 'Gross U...",2.35 : 1,[United States],"[English, French]","[Columbia Pictures, Castle Rock Entertainment,...","December 11, 1992 (United States)",[],

In [19]:
df["title"] = df["title"].replace("^[^.]+. ", "", regex=True)
df.head()

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,awards_and_nominations,cast,box_office,aspect_ratio,countries,languages,production_companies,release_date,comentarios_ia,ai_summary
0,Once Upon a Time... in Hollywood,https://www.imdb.com/title/tt7131622/?ref_=sr_t_1,84,R,2019,2h 41m,7.6,(930K),As Hollywood's Golden Age is winding down duri...,[Quentin Tarantino],...,146 wins & 377 nominations total,"[Leonardo DiCaprio, Brad Pitt, Margot Robbie, ...","{'Budget': '$90,000,000 (estimated)', 'Gross U...",2.39 : 1,"[United States, United Kingdom, China]","[English, Italian, Spanish, German]","[Columbia Pictures, Bona Film Group, Heyday Fi...","July 26, 2019 (United States)","[Authentic emotion positive sentiment, Charact...",Reviewers say 'Once Upon a Time in Hollywood' ...
1,Mission: Impossible - Dead Reckoning Part One,https://www.imdb.com/title/tt9603212/?ref_=sr_t_2,81,PG-13,2023,2h 43m,7.6,(313K),Ethan Hunt and his IMF team must track down a ...,[Christopher McQuarrie],...,18 wins & 68 nominations total,"[Tom Cruise, Hayley Atwell, Ving Rhames, Simon...","{'Budget': '$291,000,000 (estimated)', 'Gross ...",2.39 : 1,[United States],"[English, Italian, Russian, French]","[Paramount Pictures, Skydance Media, TC Produc...","July 12, 2023 (United States)","[Action sequences positive sentiment, Sound de...",Reviewers say 'Mission: Impossible - Dead Reck...
2,John Wick: Chapter 4,https://www.imdb.com/title/tt10366206/?ref_=sr...,78,R,2023,2h 49m,7.6,(394K),John Wick uncovers a path to defeating The Hig...,[Chad Stahelski],...,38 wins & 51 nominations total,"[Keanu Reeves, Laurence Fishburne, George Geor...","{'Budget': '$100,000,000 (estimated)', 'Gross ...",2.39 : 1,"[United States, Germany]","[English, Japanese, Russian, French, Spanish, ...","[Lionsgate, Thunder Road Pictures, 87Eleven En...","March 24, 2023 (United States)","[Action sequences positive sentiment, Cinemato...",Reviewers say 'John Wick: Chapter 4' is lauded...
3,The Fifth Element,https://www.imdb.com/title/tt0119116/?ref_=sr_t_4,52,PG-13,1997,2h 6m,7.6,(534K),"In the colorful future, cabdriver Korben Dalla...",[Luc Besson],...,10 wins & 39 nominations total,"[Bruce Willis, Milla Jovovich, Gary Oldman, Ia...","{'Budget': 'FRF 75,210,000 (estimated)', 'Gros...",2.39 : 1,"[France, United Kingdom]","[English, Swedish, German, Arabic, Egyptian (A...","[Gaumont, Pinewood Studios]","May 9, 1997 (United States)",[],
4,Watchmen,https://www.imdb.com/title/tt0409459/?ref_=sr_t_5,56,R,2009,2h 42m,7.6,(604K),"In a version of 1985 where superheroes exist, ...",[Zack Snyder],...,12 wins & 24 nominations total,"[Jackie Earle Haley, Patrick Wilson, Carla Gug...","{'Budget': '$130,000,000 (estimated)', 'Gross ...",2.39 : 1,[United States],[English],"[Warner Bros., Paramount Pictures, Legendary E...","March 6, 2009 (United States)","[Ambitious positive sentiment, Cinematography ...",Reviewers say 'Watchmen' is acclaimed for its ...

In [20]:
def parse_duration(value: str) -> int:
    mins = 0
    for component in value.split(" "):
        if component.endswith("h"):
            hours = int(component[:-1])
            mins += hours * 60
        elif component.endswith("m"):
            minutes = int(component[:-1])
            mins += minutes

    return mins


df["duration_mins"] = df["duration"].apply(parse_duration)
df.head()

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,cast,box_office,aspect_ratio,countries,languages,production_companies,release_date,comentarios_ia,ai_summary,duration_mins
0,Once Upon a Time... in Hollywood,https://www.imdb.com/title/tt7131622/?ref_=sr_t_1,84,R,2019,2h 41m,7.6,(930K),As Hollywood's Golden Age is winding down duri...,[Quentin Tarantino],...,"[Leonardo DiCaprio, Brad Pitt, Margot Robbie, ...","{'Budget': '$90,000,000 (estimated)', 'Gross U...",2.39 : 1,"[United States, United Kingdom, China]","[English, Italian, Spanish, German]","[Columbia Pictures, Bona Film Group, Heyday Fi...","July 26, 2019 (United States)","[Authentic emotion positive sentiment, Charact...",Reviewers say 'Once Upon a Time in Hollywood' ...,161
1,Mission: Impossible - Dead Reckoning Part One,https://www.imdb.com/title/tt9603212/?ref_=sr_t_2,81,PG-13,2023,2h 43m,7.6,(313K),Ethan Hunt and his IMF team must track down a ...,[Christopher McQuarrie],...,"[Tom Cruise, Hayley Atwell, Ving Rhames, Simon...","{'Budget': '$291,000,000 (estimated)', 'Gross ...",2.39 : 1,[United States],"[English, Italian, Russian, French]","[Paramount Pictures, Skydance Media, TC Produc...","July 12, 2023 (United States)","[Action sequences positive sentiment, Sound de...",Reviewers say 'Mission: Impossible - Dead Reck...,163
2,John Wick: Chapter 4,https://www.imdb.com/title/tt10366206/?ref_=sr...,78,R,2023,2h 49m,7.6,(394K),John Wick uncovers a path to defeating The Hig...,[Chad Stahelski],...,"[Keanu Reeves, Laurence Fishburne, George Geor...","{'Budget': '$100,000,000 (estimated)', 'Gross ...",2.39 : 1,"[United States, Germany]","[English, Japanese, Russian, French, Spanish, ...","[Lionsgate, Thunder Road Pictures, 87Eleven En...","March 24, 2023 (United States)","[Action sequences positive sentiment, Cinemato...",Reviewers say 'John Wick: Chapter 4' is lauded...,169
3,The Fifth Element,https://www.imdb.com/title/tt0119116/?ref_=sr_t_4,52,PG-13,1997,2h 6m,7.6,(534K),"In the colorful future, cabdriver Korben Dalla...",[Luc Besson],...,"[Bruce Willis, Milla Jovovich, Gary Oldman, Ia...","{'Budget': 'FRF 75,210,000 (estimated)', 'Gros...",2.39 : 1,"[France, United Kingdom]","[English, Swedish, German, Arabic, Egyptian (A...","[Gaumont, Pinewood Studios]","May 9, 1997 (United States)",[],,126
4,Watchmen,https://www.imdb.com/title/tt0409459/?ref_=sr_t_5,56,R,2009,2h 42m,7.6,(604K),"In a version of 1985 where superheroes exist, ...",[Zack Snyder],...,"[Jackie Earle Haley, Patrick Wilson, Carla Gug...","{'Budget': '$130,000,000 (estimated)', 'Gross ...",2.39 : 1,[United States],[English],"[Warner Bros., Paramount Pictures, Legendary E...","March 6, 2009 (United States)","[Ambitious positive sentiment, Cinematography ...",Reviewers say 'Watchmen' is acclaimed for its ...,162

In [21]:
df["budget"] = df["box_office"].map(lambda x: x.get("Budget", 0))
df["gross_world"] = df["box_office"].map(lambda x: x.get("Gross worldwide", 0))
df["gross_usa_canada"] = df["box_office"].map(lambda x: x.get("Gross US & Canada", 0))
df["opening_weekend_usa_canada"] = df["box_office"].map(lambda x: x.get("Opening weekend US & Canada", None))

df

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,languages,production_companies,release_date,comentarios_ia,ai_summary,duration_mins,budget,gross_world,gross_usa_canada,opening_weekend_usa_canada
0,Once Upon a Time... in Hollywood,https://www.imdb.com/title/tt7131622/?ref_=sr_t_1,84,R,2019,2h 41m,7.6,(930K),As Hollywood's Golden Age is winding down duri...,[Quentin Tarantino],...,"[English, Italian, Spanish, German]","[Columbia Pictures, Bona Film Group, Heyday Fi...","July 26, 2019 (United States)","[Authentic emotion positive sentiment, Charact...",Reviewers say 'Once Upon a Time in Hollywood' ...,161,"$90,000,000 (estimated)","$392,105,159","$142,502,728","$41,082,018Jul 28, 2019"
1,Mission: Impossible - Dead Reckoning Part One,https://www.imdb.com/title/tt9603212/?ref_=sr_t_2,81,PG-13,2023,2h 43m,7.6,(313K),Ethan Hunt and his IMF team must track down a ...,[Christopher McQuarrie],...,"[English, Italian, Russian, French]","[Paramount Pictures, Skydance Media, TC Produc...","July 12, 2023 (United States)","[Action sequences positive sentiment, Sound de...",Reviewers say 'Mission: Impossible - Dead Reck...,163,"$291,000,000 (estimated)","$571,125,435","$172,640,980","$54,688,347Jul 16, 2023"
2,John Wick: Chapter 4,https://www.imdb.com/title/tt10366206/?ref_=sr...,78,R,2023,2h 49m,7.6,(394K),John Wick uncovers a path to defeating The Hig...,[Chad Stahelski],...,"[English, Japanese, Russian, French, Spanish, ...","[Lionsgate, Thunder Road Pictures, 87Eleven En...","March 24, 2023 (United States)","[Action sequences positive sentiment, Cinemato...",Reviewers say 'John Wick: Chapter 4' is lauded...,169,"$100,000,000 (estimated)","$447,142,521","$187,131,806","$73,817,950Mar 26, 2023"
3,The Fifth Element,https://www.imdb.com/title/tt0119116/?ref_=sr_t_4,52,PG-13,1997,2h 6m,7.6,(534K),"In the colorful future, cabdriver Korben Dalla...",[Luc Besson],...,"[English, Swedish, German, Arabic, Egyptian (A...","[Gaumont, Pinewood Studios]","May 9, 1997 (United States)",[],,126,"FRF 75,210,000 (estimated)","$263,920,180","$63,820,180","$17,031,345May 11, 1997"
4,Watchmen,https://www.imdb.com/title/tt0409459/?ref_=sr_t_5,56,R,2009,2h 42m,7.6,(604K),"In a version of 1985 where superheroes exist, ...",[Zack Snyder],...,[English],"[Warner Bros., Paramount Pictures, Legendary E...","March 6, 2009 (United States)","[Ambitious positive sentiment, Cinematography ...",Reviewers say 'Watchmen' is acclaimed for its ...,162,"$130,000,000 (estimated)","$185,382,813","$107,509,799","$55,214,334Mar 8, 2009"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,Home Alone,https://www.imdb.com/title/tt0099785/?ref_=sr_...,63,PG,1990,1h 43m,7.7,(707K),"An eight-year-old troublemaker, mistakenly lef...",[Chris Columbus],...,"[English, French]","[Twentieth Century Fox, Hughes Entertainment]","November 16, 1990 (United States)",[],,103,"$18,000,000 (estimated)","$476,684,675","$285,761,243","$17,081,997Nov 18, 1990"
66,Blue Velvet,https://www.imdb.com/title/tt0090756/?ref_=sr_...,75,R,1986,2h,7.7,(237K),The discovery of a severed human ear found in ...,[David Lynch],...,[English],[De Laurentiis Entertainment Group (DEG)],"October 23, 1986 (Italy)",[],,120,"$6,000,000 (estimated)","$8,675,306","$8,551,228","$789,409Sep 21, 1986"
67,When Harry Met Sally...,https://www.imdb.com/title/tt0098635/?ref_=sr_...,76,R,1989,1h 35m,7.7,(260K),Harry and Sally have known each other for year...,[Rob Reiner],...,[English],"[Castle Rock Entertainment, Nelson Entertainme...","July 21, 1989 (United States)",[],,95,"$16,000,000 (estimated)","$93,275,428","$93,117,425","$1,094,453Jul 16, 1989"
68,"O Brother, Where Art Thou?",https://www.imdb.com/title/tt0190590/?ref_=sr_...,69,PG-13,2000,1h 47m,7.7,(345K),"In the deep south during the 1930s, three esca...","[Joel Coen, Ethan Coen]",...,[English],"[Touchstone Pictures, Universal Pictures, Stud...","February 2, 2001 (United States)",[],,107,"$26,000,000 (estimated)","$71,877,090","$45,512,588","$195,104Dec 25, 2000"
69,A Few Good Men,https://www.imdb.com/title/tt0104257/?ref_=sr_...,62,R,1992,2h 18m,7.7,(308K),A military lawyer intends to prove that two US...,[Rob Reiner],...,"[English, French]","[Columbia Pictures, Castle Rock Entertainment,...","December 11, 1992 (United States)",[],,138,"$41,000,000 (estimated)","$243,240,178","$141,340,178","$15,517,468Dec 13, 1992"

In [22]:
import re

def parse_money(value: str) -> float:
    if value is None:
        return None

    value = value.rstrip(" (estimated)")
    value = re.sub(r",", "", value)

    if value.startswith("$"):
        return float(value[1:])
    if value.startswith("FRF"):
        return float(value[4:]) * 0.17871603 # https://www.xe.com/currencyconverter/convert/?Amount=1&From=FRF&To=USD
    if value.startswith("€"):
        return float(value[1:]) * 1.1722995
    if value.startswith("DEM"):
        return float(value[4:]) * 0.59939338
    else:
        return None

def get_faltantes(cdf, original, target):
    return cdf[cdf[target].isna() & ~(cdf[original].isna())]

df["budget_usd"] = df["budget"].map(parse_money)
get_faltantes(df, "budget", "budget_usd")

Empty DataFrame
Columns: [title, url, metacritic_score, rating, year, duration, rating_stars, voters, description, director, writers, stars, storyline, genres, genres_ext, awards_and_nominations, cast, box_office, aspect_ratio, countries, languages, production_companies, release_date, comentarios_ia, ai_summary, duration_mins, budget, gross_world, gross_usa_canada, opening_weekend_usa_canada, budget_usd]
Index: []

[0 rows x 31 columns]

In [23]:
df["gross_world_usd"] = df["gross_world"].map(parse_money)
get_faltantes(df, "gross_world", "gross_world_usd")

Empty DataFrame
Columns: [title, url, metacritic_score, rating, year, duration, rating_stars, voters, description, director, writers, stars, storyline, genres, genres_ext, awards_and_nominations, cast, box_office, aspect_ratio, countries, languages, production_companies, release_date, comentarios_ia, ai_summary, duration_mins, budget, gross_world, gross_usa_canada, opening_weekend_usa_canada, budget_usd, gross_world_usd]
Index: []

[0 rows x 32 columns]

In [24]:
df["gross_usa_canada_usd"] = df["gross_usa_canada"].map(parse_money)
get_faltantes(df, "gross_usa_canada", "gross_usa_canada_usd")

Empty DataFrame
Columns: [title, url, metacritic_score, rating, year, duration, rating_stars, voters, description, director, writers, stars, storyline, genres, genres_ext, awards_and_nominations, cast, box_office, aspect_ratio, countries, languages, production_companies, release_date, comentarios_ia, ai_summary, duration_mins, budget, gross_world, gross_usa_canada, opening_weekend_usa_canada, budget_usd, gross_world_usd, gross_usa_canada_usd]
Index: []

[0 rows x 33 columns]

In [25]:
def split_at_date(value: str) -> (str, str):
    idx = 0

    if value is None:
        return (None, None)

    while idx < len(value):
        try:
            if value[idx].isupper() and value[idx-1].isnumeric():
                return value[:idx], value[idx:]
        except IndexError:
            return value[:idx], value[idx:]

        idx += 1

# df["opening_weekend_usa_canada_usd"] = df["opening_weekend_usa_canada"].map(parse_money)
# get_faltantes(df, "opening_weekend_usa_canada", "opening_weekend_usa_canada_usd")

open_info = df["opening_weekend_usa_canada"].map(split_at_date)
df["opening_weekend_usa_canada_date"] = open_info.map(lambda x: x[1])
df["opening_weekend_usa_canada_usd"] = open_info.map(lambda x: parse_money(x[0]))

get_faltantes(df, "opening_weekend_usa_canada", "opening_weekend_usa_canada_usd")

Empty DataFrame
Columns: [title, url, metacritic_score, rating, year, duration, rating_stars, voters, description, director, writers, stars, storyline, genres, genres_ext, awards_and_nominations, cast, box_office, aspect_ratio, countries, languages, production_companies, release_date, comentarios_ia, ai_summary, duration_mins, budget, gross_world, gross_usa_canada, opening_weekend_usa_canada, budget_usd, gross_world_usd, gross_usa_canada_usd, opening_weekend_usa_canada_date, opening_weekend_usa_canada_usd]
Index: []

[0 rows x 35 columns]

In [26]:
df.head()

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,duration_mins,budget,gross_world,gross_usa_canada,opening_weekend_usa_canada,budget_usd,gross_world_usd,gross_usa_canada_usd,opening_weekend_usa_canada_date,opening_weekend_usa_canada_usd
0,Once Upon a Time... in Hollywood,https://www.imdb.com/title/tt7131622/?ref_=sr_t_1,84,R,2019,2h 41m,7.6,(930K),As Hollywood's Golden Age is winding down duri...,[Quentin Tarantino],...,161,"$90,000,000 (estimated)","$392,105,159","$142,502,728","$41,082,018Jul 28, 2019",9.000000e+07,392105159.0,142502728.0,"Jul 28, 2019",41082018.0
1,Mission: Impossible - Dead Reckoning Part One,https://www.imdb.com/title/tt9603212/?ref_=sr_t_2,81,PG-13,2023,2h 43m,7.6,(313K),Ethan Hunt and his IMF team must track down a ...,[Christopher McQuarrie],...,163,"$291,000,000 (estimated)","$571,125,435","$172,640,980","$54,688,347Jul 16, 2023",2.910000e+08,571125435.0,172640980.0,"Jul 16, 2023",54688347.0
2,John Wick: Chapter 4,https://www.imdb.com/title/tt10366206/?ref_=sr...,78,R,2023,2h 49m,7.6,(394K),John Wick uncovers a path to defeating The Hig...,[Chad Stahelski],...,169,"$100,000,000 (estimated)","$447,142,521","$187,131,806","$73,817,950Mar 26, 2023",1.000000e+08,447142521.0,187131806.0,"Mar 26, 2023",73817950.0
3,The Fifth Element,https://www.imdb.com/title/tt0119116/?ref_=sr_t_4,52,PG-13,1997,2h 6m,7.6,(534K),"In the colorful future, cabdriver Korben Dalla...",[Luc Besson],...,126,"FRF 75,210,000 (estimated)","$263,920,180","$63,820,180","$17,031,345May 11, 1997",1.344123e+07,263920180.0,63820180.0,"May 11, 1997",17031345.0
4,Watchmen,https://www.imdb.com/title/tt0409459/?ref_=sr_t_5,56,R,2009,2h 42m,7.6,(604K),"In a version of 1985 where superheroes exist, ...",[Zack Snyder],...,162,"$130,000,000 (estimated)","$185,382,813","$107,509,799","$55,214,334Mar 8, 2009",1.300000e+08,185382813.0,107509799.0,"Mar 8, 2009",55214334.0

In [27]:
def parse_awards(value: str) -> (int, int):
    words = value.split(" ")
    nominations = 0
    awards = 0

    for idx, word in enumerate(words):
        if word.startswith("win"):
            awards = int(words[idx-1])
        elif word.startswith("nomina"):
            nominations = int(words[idx-1])

    return awards, nominations

df["awards"] = df["awards_and_nominations"].map(lambda x: parse_awards(x)[0])
df["nominations"] = df["awards_and_nominations"].map(lambda x: parse_awards(x)[1])

df[["awards_and_nominations", "awards", "nominations"]].head()

             awards_and_nominations  awards  nominations
0  146 wins & 377 nominations total     146          377
1    18 wins & 68 nominations total      18           68
2    38 wins & 51 nominations total      38           51
3    10 wins & 39 nominations total      10           39
4    12 wins & 24 nominations total      12           24

In [28]:
df["voters_int"] = df["voters"].replace(r"\(|\)| ", "", regex=True).replace("K", "000", regex=True).replace("M", "000000", regex=True).astype("int")

df[["voters", "voters_int"]].head()

    voters  voters_int
0   (930K)      930000
1   (313K)      313000
2   (394K)      394000
3   (534K)      534000
4   (604K)      604000

In [29]:
df["rating_stars_int"] = df["rating_stars"].astype("float")
df[["rating_stars", "rating_stars_int"]].head()

  rating_stars  rating_stars_int
0          7.6               7.6
1          7.6               7.6
2          7.6               7.6
3          7.6               7.6
4          7.6               7.6

In [30]:
df.to_parquet(utils.find_project_root() / "data" / "inter" / "stage2.parquet")