In [61]:
import pandas as pd
from common import utils

In [62]:
df = pd.read_parquet(utils.find_project_root() / "data" / "raw" / "stage1.parquet")

In [63]:
df

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,awards_and_nominations,cast,box_office,aspect_ratio,countries,languages,production_companies,release_date,comentarios_ia,ai_summary
0,1. Once Upon a Time... in Hollywood,https://www.imdb.com/title/tt7131622/?ref_=sr_t_1,84,R,2019,2h 41m,7.6,(930K),As Hollywood's Golden Age is winding down duri...,[Quentin Tarantino],...,146 wins & 377 nominations total,"[Leonardo DiCaprio, Brad Pitt, Margot Robbie, ...","{'Budget': '$90,000,000 (estimated)', 'Goofs':...",2.39 : 1,"[United States, United Kingdom, China]","[English, Italian, Spanish, German]","[Columbia Pictures, Bona Film Group, Heyday Fi...","July 26, 2019 (United States)","[Authentic emotion positive sentiment, Charact...",Reviewers say 'Once Upon a Time in Hollywood' ...
1,2. Mission: Impossible - Dead Reckoning Part One,https://www.imdb.com/title/tt9603212/?ref_=sr_t_2,81,PG-13,2023,2h 43m,7.6,(313K),Ethan Hunt and his IMF team must track down a ...,[Christopher McQuarrie],...,18 wins & 68 nominations total,"[Tom Cruise, Hayley Atwell, Ving Rhames, Simon...","{'Budget': '$291,000,000 (estimated)', 'Goofs'...",2.39 : 1,[United States],"[English, Italian, Russian, French]","[Paramount Pictures, Skydance Media, TC Produc...","July 12, 2023 (United States)","[Action sequences positive sentiment, Sound de...",Reviewers say 'Mission: Impossible - Dead Reck...
2,3. John Wick: Chapter 4,https://www.imdb.com/title/tt10366206/?ref_=sr...,78,R,2023,2h 49m,7.6,(394K),John Wick uncovers a path to defeating The Hig...,[Chad Stahelski],...,38 wins & 51 nominations total,"[Keanu Reeves, Laurence Fishburne, George Geor...","{'Budget': '$100,000,000 (estimated)', 'Goofs'...",2.39 : 1,"[United States, Germany]","[English, Japanese, Russian, French, Spanish, ...","[Lionsgate, Thunder Road Pictures, 87Eleven En...","March 24, 2023 (United States)","[Action sequences positive sentiment, Cinemato...",Reviewers say 'John Wick: Chapter 4' is lauded...
3,4. The Fifth Element,https://www.imdb.com/title/tt0119116/?ref_=sr_t_4,52,PG-13,1997,2h 6m,7.6,(534K),"In the colorful future, cabdriver Korben Dalla...",[Luc Besson],...,10 wins & 39 nominations total,"[Bruce Willis, Milla Jovovich, Gary Oldman, Ia...","{'Budget': 'FRF 75,210,000 (estimated)', 'Goof...",2.39 : 1,"[France, United Kingdom]","[English, Swedish, German, Arabic, Egyptian (A...","[Gaumont, Pinewood Studios]","May 9, 1997 (United States)",[],
4,5. Watchmen,https://www.imdb.com/title/tt0409459/?ref_=sr_t_5,56,R,2009,2h 42m,7.6,(604K),"In a version of 1985 where superheroes exist, ...",[Zack Snyder],...,12 wins & 24 nominations total,"[Jackie Earle Haley, Patrick Wilson, Carla Gug...","{'Budget': '$130,000,000 (estimated)', 'Goofs'...",2.39 : 1,[United States],[English],"[Warner Bros., Paramount Pictures, Legendary E...","March 6, 2009 (United States)","[Ambitious positive sentiment, Cinematography ...",Reviewers say 'Watchmen' is acclaimed for its ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996. The Godfather Part II,https://www.imdb.com/title/tt0071562/?ref_=sr_...,90,R,1974,3h 22m,9.0,(1.5M),The early life and career of Vito Corleone in ...,[Francis Ford Coppola],...,17 wins & 21 nominations total,"[Al Pacino, Robert De Niro, Robert Duvall, Dia...","{'Budget': '$13,000,000 (estimated)', 'Goofs':...",1.85 : 1,[United States],"[English, Italian, Spanish, Latin, Sicilian]","[Paramount Pictures, The Coppola Company, Amer...","December 18, 1974 (United States)","[Atmospheric positive sentiment, Cinematograph...",Reviewers say 'The Godfather Part II' is accla...
996,997. The Lord of the Rings: The Return of the ...,https://www.imdb.com/title/tt0167260/?ref_=sr_...,94,PG-13,2003,3h 21m,9.0,(2.1M),Gandalf and Aragorn lead the World of Men agai...,[Peter Jackson],...,215 wins & 124 nominations total,"[Elijah Wood, Viggo Mortensen, Ian McKellen, O...","{'Budget': '$94,000,000 (estimated)', 'Goofs':...",2.39 : 1,"[New Zealand, United States]","[English, Quenya, Old English, Sindarin]","[New Line Cinema, WingNut Films, The Saul Zaen...","December 17, 2003 (United States)","[Action sequences positive sentiment, Atmosphe...","Reviewers say 'The Lord of the Rings' trilogy,..."
997,998. The Dark Knight,https://www.imdb.com/title/tt0468569/?ref_=sr_...,85,PG-13,2008,2h 32m,9.1,(3.1M),When a menace known as the Joker wreaks havoc ...,[Christopher Nolan],...,163 wins & 165 nominations total,"[Christian Bale, Heath Ledger, Aaron Eckhart, ...","{'Budget': '$185,000,000 (estimated)', 'Goofs'...",2.39 : 1,"[United States, United Kingdom]","[English, Mandarin]","[Warner Bros., Legendary Entertainment, Syncopy]","July 18, 2008 (United States)","[Action sequences positive sentiment, Cinemato...",Reviewers say 'The Dark Knight' is celebrated ...
998,999. The Godfather,https://www.imdb.com/title/tt0068646/?ref_=sr_...,100,R,1972,2h 55m,9.2,(2.2M),The aging patriarch of an organized crime dyna...,[Francis Ford Coppola],...,31 wins & 31 nominations total,"[Marlon Brando, Al Pacino, James Caan, Diane K...","{'Budget': '$6,000,000 (estimated)', 'Goofs': ...",1.85 : 1,[United States],"[English, Italian, Latin]","[Paramount Pictures, Albert S. Ruddy Productio...","March 24, 1972 (United States)","[Atmospheric positive sentiment, Authentic emo...",Reviewers say 'The Godfather' is acclaimed for...
999,1000. The Shawshank Redemption,https://www.imdb.com/title/tt0111161/?ref_=sr_...,82,R,1994,2h 22m,9.3,(3.1M),A banker convicted of uxoricide forms a friend...,[Frank Darabont],...,21 wins & 42 nominations total,"[Tim Robbins, Morgan Freeman, Bob Gunton, Will...","{'Budget': '$25,000,000 (estimated)', 'Goofs':...",1.85 : 1,[United States],[English],[Castle Rock Entertainment],"October 14, 1994 (United States)","[Authentic emotion positive sentiment, Charact...",Reviewers say 'The Shawshank Redemption' is ce...

In [64]:
df["title"] = df["title"].replace("^[^.]+. ", "", regex=True)
df.head()

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,awards_and_nominations,cast,box_office,aspect_ratio,countries,languages,production_companies,release_date,comentarios_ia,ai_summary
0,Once Upon a Time... in Hollywood,https://www.imdb.com/title/tt7131622/?ref_=sr_t_1,84,R,2019,2h 41m,7.6,(930K),As Hollywood's Golden Age is winding down duri...,[Quentin Tarantino],...,146 wins & 377 nominations total,"[Leonardo DiCaprio, Brad Pitt, Margot Robbie, ...","{'Budget': '$90,000,000 (estimated)', 'Goofs':...",2.39 : 1,"[United States, United Kingdom, China]","[English, Italian, Spanish, German]","[Columbia Pictures, Bona Film Group, Heyday Fi...","July 26, 2019 (United States)","[Authentic emotion positive sentiment, Charact...",Reviewers say 'Once Upon a Time in Hollywood' ...
1,Mission: Impossible - Dead Reckoning Part One,https://www.imdb.com/title/tt9603212/?ref_=sr_t_2,81,PG-13,2023,2h 43m,7.6,(313K),Ethan Hunt and his IMF team must track down a ...,[Christopher McQuarrie],...,18 wins & 68 nominations total,"[Tom Cruise, Hayley Atwell, Ving Rhames, Simon...","{'Budget': '$291,000,000 (estimated)', 'Goofs'...",2.39 : 1,[United States],"[English, Italian, Russian, French]","[Paramount Pictures, Skydance Media, TC Produc...","July 12, 2023 (United States)","[Action sequences positive sentiment, Sound de...",Reviewers say 'Mission: Impossible - Dead Reck...
2,John Wick: Chapter 4,https://www.imdb.com/title/tt10366206/?ref_=sr...,78,R,2023,2h 49m,7.6,(394K),John Wick uncovers a path to defeating The Hig...,[Chad Stahelski],...,38 wins & 51 nominations total,"[Keanu Reeves, Laurence Fishburne, George Geor...","{'Budget': '$100,000,000 (estimated)', 'Goofs'...",2.39 : 1,"[United States, Germany]","[English, Japanese, Russian, French, Spanish, ...","[Lionsgate, Thunder Road Pictures, 87Eleven En...","March 24, 2023 (United States)","[Action sequences positive sentiment, Cinemato...",Reviewers say 'John Wick: Chapter 4' is lauded...
3,The Fifth Element,https://www.imdb.com/title/tt0119116/?ref_=sr_t_4,52,PG-13,1997,2h 6m,7.6,(534K),"In the colorful future, cabdriver Korben Dalla...",[Luc Besson],...,10 wins & 39 nominations total,"[Bruce Willis, Milla Jovovich, Gary Oldman, Ia...","{'Budget': 'FRF 75,210,000 (estimated)', 'Goof...",2.39 : 1,"[France, United Kingdom]","[English, Swedish, German, Arabic, Egyptian (A...","[Gaumont, Pinewood Studios]","May 9, 1997 (United States)",[],
4,Watchmen,https://www.imdb.com/title/tt0409459/?ref_=sr_t_5,56,R,2009,2h 42m,7.6,(604K),"In a version of 1985 where superheroes exist, ...",[Zack Snyder],...,12 wins & 24 nominations total,"[Jackie Earle Haley, Patrick Wilson, Carla Gug...","{'Budget': '$130,000,000 (estimated)', 'Goofs'...",2.39 : 1,[United States],[English],"[Warner Bros., Paramount Pictures, Legendary E...","March 6, 2009 (United States)","[Ambitious positive sentiment, Cinematography ...",Reviewers say 'Watchmen' is acclaimed for its ...

In [65]:
def parse_duration(value: str) -> int:
    mins = 0
    for component in value.split(" "):
        if component.endswith("h"):
            hours = int(component[:-1])
            mins += hours * 60
        elif component.endswith("m"):
            minutes = int(component[:-1])
            mins += minutes

    return mins


df["duration_mins"] = df["duration"].apply(parse_duration)
df.head()

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,cast,box_office,aspect_ratio,countries,languages,production_companies,release_date,comentarios_ia,ai_summary,duration_mins
0,Once Upon a Time... in Hollywood,https://www.imdb.com/title/tt7131622/?ref_=sr_t_1,84,R,2019,2h 41m,7.6,(930K),As Hollywood's Golden Age is winding down duri...,[Quentin Tarantino],...,"[Leonardo DiCaprio, Brad Pitt, Margot Robbie, ...","{'Budget': '$90,000,000 (estimated)', 'Goofs':...",2.39 : 1,"[United States, United Kingdom, China]","[English, Italian, Spanish, German]","[Columbia Pictures, Bona Film Group, Heyday Fi...","July 26, 2019 (United States)","[Authentic emotion positive sentiment, Charact...",Reviewers say 'Once Upon a Time in Hollywood' ...,161
1,Mission: Impossible - Dead Reckoning Part One,https://www.imdb.com/title/tt9603212/?ref_=sr_t_2,81,PG-13,2023,2h 43m,7.6,(313K),Ethan Hunt and his IMF team must track down a ...,[Christopher McQuarrie],...,"[Tom Cruise, Hayley Atwell, Ving Rhames, Simon...","{'Budget': '$291,000,000 (estimated)', 'Goofs'...",2.39 : 1,[United States],"[English, Italian, Russian, French]","[Paramount Pictures, Skydance Media, TC Produc...","July 12, 2023 (United States)","[Action sequences positive sentiment, Sound de...",Reviewers say 'Mission: Impossible - Dead Reck...,163
2,John Wick: Chapter 4,https://www.imdb.com/title/tt10366206/?ref_=sr...,78,R,2023,2h 49m,7.6,(394K),John Wick uncovers a path to defeating The Hig...,[Chad Stahelski],...,"[Keanu Reeves, Laurence Fishburne, George Geor...","{'Budget': '$100,000,000 (estimated)', 'Goofs'...",2.39 : 1,"[United States, Germany]","[English, Japanese, Russian, French, Spanish, ...","[Lionsgate, Thunder Road Pictures, 87Eleven En...","March 24, 2023 (United States)","[Action sequences positive sentiment, Cinemato...",Reviewers say 'John Wick: Chapter 4' is lauded...,169
3,The Fifth Element,https://www.imdb.com/title/tt0119116/?ref_=sr_t_4,52,PG-13,1997,2h 6m,7.6,(534K),"In the colorful future, cabdriver Korben Dalla...",[Luc Besson],...,"[Bruce Willis, Milla Jovovich, Gary Oldman, Ia...","{'Budget': 'FRF 75,210,000 (estimated)', 'Goof...",2.39 : 1,"[France, United Kingdom]","[English, Swedish, German, Arabic, Egyptian (A...","[Gaumont, Pinewood Studios]","May 9, 1997 (United States)",[],,126
4,Watchmen,https://www.imdb.com/title/tt0409459/?ref_=sr_t_5,56,R,2009,2h 42m,7.6,(604K),"In a version of 1985 where superheroes exist, ...",[Zack Snyder],...,"[Jackie Earle Haley, Patrick Wilson, Carla Gug...","{'Budget': '$130,000,000 (estimated)', 'Goofs'...",2.39 : 1,[United States],[English],"[Warner Bros., Paramount Pictures, Legendary E...","March 6, 2009 (United States)","[Ambitious positive sentiment, Cinematography ...",Reviewers say 'Watchmen' is acclaimed for its ...,162

In [66]:
df["budget"] = df["box_office"].map(lambda x: x.get("Budget", 0))
df["gross_world"] = df["box_office"].map(lambda x: x.get("Gross worldwide", 0))
df["gross_usa_canada"] = df["box_office"].map(lambda x: x.get("Gross US & Canada", 0))
df["opening_weekend_usa_canada"] = df["box_office"].map(lambda x: x.get("Opening weekend US & Canada", None))

df

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,languages,production_companies,release_date,comentarios_ia,ai_summary,duration_mins,budget,gross_world,gross_usa_canada,opening_weekend_usa_canada
0,Once Upon a Time... in Hollywood,https://www.imdb.com/title/tt7131622/?ref_=sr_t_1,84,R,2019,2h 41m,7.6,(930K),As Hollywood's Golden Age is winding down duri...,[Quentin Tarantino],...,"[English, Italian, Spanish, German]","[Columbia Pictures, Bona Film Group, Heyday Fi...","July 26, 2019 (United States)","[Authentic emotion positive sentiment, Charact...",Reviewers say 'Once Upon a Time in Hollywood' ...,161,"$90,000,000 (estimated)","$392,105,159","$142,502,728","$41,082,018Jul 28, 2019"
1,Mission: Impossible - Dead Reckoning Part One,https://www.imdb.com/title/tt9603212/?ref_=sr_t_2,81,PG-13,2023,2h 43m,7.6,(313K),Ethan Hunt and his IMF team must track down a ...,[Christopher McQuarrie],...,"[English, Italian, Russian, French]","[Paramount Pictures, Skydance Media, TC Produc...","July 12, 2023 (United States)","[Action sequences positive sentiment, Sound de...",Reviewers say 'Mission: Impossible - Dead Reck...,163,"$291,000,000 (estimated)","$571,125,435","$172,640,980","$54,688,347Jul 16, 2023"
2,John Wick: Chapter 4,https://www.imdb.com/title/tt10366206/?ref_=sr...,78,R,2023,2h 49m,7.6,(394K),John Wick uncovers a path to defeating The Hig...,[Chad Stahelski],...,"[English, Japanese, Russian, French, Spanish, ...","[Lionsgate, Thunder Road Pictures, 87Eleven En...","March 24, 2023 (United States)","[Action sequences positive sentiment, Cinemato...",Reviewers say 'John Wick: Chapter 4' is lauded...,169,"$100,000,000 (estimated)","$447,142,521","$187,131,806","$73,817,950Mar 26, 2023"
3,The Fifth Element,https://www.imdb.com/title/tt0119116/?ref_=sr_t_4,52,PG-13,1997,2h 6m,7.6,(534K),"In the colorful future, cabdriver Korben Dalla...",[Luc Besson],...,"[English, Swedish, German, Arabic, Egyptian (A...","[Gaumont, Pinewood Studios]","May 9, 1997 (United States)",[],,126,"FRF 75,210,000 (estimated)","$263,920,180","$63,820,180","$17,031,345May 11, 1997"
4,Watchmen,https://www.imdb.com/title/tt0409459/?ref_=sr_t_5,56,R,2009,2h 42m,7.6,(604K),"In a version of 1985 where superheroes exist, ...",[Zack Snyder],...,[English],"[Warner Bros., Paramount Pictures, Legendary E...","March 6, 2009 (United States)","[Ambitious positive sentiment, Cinematography ...",Reviewers say 'Watchmen' is acclaimed for its ...,162,"$130,000,000 (estimated)","$185,382,813","$107,509,799","$55,214,334Mar 8, 2009"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,The Godfather Part II,https://www.imdb.com/title/tt0071562/?ref_=sr_...,90,R,1974,3h 22m,9.0,(1.5M),The early life and career of Vito Corleone in ...,[Francis Ford Coppola],...,"[English, Italian, Spanish, Latin, Sicilian]","[Paramount Pictures, The Coppola Company, Amer...","December 18, 1974 (United States)","[Atmospheric positive sentiment, Cinematograph...",Reviewers say 'The Godfather Part II' is accla...,202,"$13,000,000 (estimated)","$48,105,107","$47,834,595","$171,417Nov 10, 2019"
996,The Lord of the Rings: The Return of the King,https://www.imdb.com/title/tt0167260/?ref_=sr_...,94,PG-13,2003,3h 21m,9.0,(2.1M),Gandalf and Aragorn lead the World of Men agai...,[Peter Jackson],...,"[English, Quenya, Old English, Sindarin]","[New Line Cinema, WingNut Films, The Saul Zaen...","December 17, 2003 (United States)","[Action sequences positive sentiment, Atmosphe...","Reviewers say 'The Lord of the Rings' trilogy,...",201,"$94,000,000 (estimated)","$1,139,427,855","$381,878,219","$72,629,713Dec 21, 2003"
997,The Dark Knight,https://www.imdb.com/title/tt0468569/?ref_=sr_...,85,PG-13,2008,2h 32m,9.1,(3.1M),When a menace known as the Joker wreaks havoc ...,[Christopher Nolan],...,"[English, Mandarin]","[Warner Bros., Legendary Entertainment, Syncopy]","July 18, 2008 (United States)","[Action sequences positive sentiment, Cinemato...",Reviewers say 'The Dark Knight' is celebrated ...,152,"$185,000,000 (estimated)","$1,009,242,873","$534,987,076","$158,411,483Jul 20, 2008"
998,The Godfather,https://www.imdb.com/title/tt0068646/?ref_=sr_...,100,R,1972,2h 55m,9.2,(2.2M),The aging patriarch of an organized crime dyna...,[Francis Ford Coppola],...,"[English, Italian, Latin]","[Paramount Pictures, Albert S. Ruddy Productio...","March 24, 1972 (United States)","[Atmospheric positive sentiment, Authentic emo...",Reviewers say 'The Godfather' is acclaimed for...,175,"$6,000,000 (estimated)","$250,595,410","$136,381,073","$302,393Mar 19, 1972"
999,The Shawshank Redemption,https://www.imdb.com/title/tt0111161/?ref_=sr_...,82,R,1994,2h 22m,9.3,(3.1M),A banker convicted of uxoricide forms a friend...,[Frank Darabont],...,[English],[Castle Rock Entertainment],"October 14, 1994 (United States)","[Authentic emotion positive sentiment, Charact...",Reviewers say 'The Shawshank Redemption' is ce...,142,"$25,000,000 (estimated)","$29,334,033","$28,767,189","$727,327Sep 25, 1994"

In [67]:
import re

def parse_money(value: str) -> float:
    if value is None:
        return None

    value = value.rstrip(" (estimated)")
    value = re.sub(r",", "", value)

    if value.startswith("$"):
        return float(value[1:])
    if value.startswith("FRF"):
        return float(value[4:]) * 0.17871603 # https://www.xe.com/currencyconverter/convert/?Amount=1&From=FRF&To=USD
    if value.startswith("€"):
        return float(value[1:]) * 1.1722995
    if value.startswith("DEM"):
        return float(value[4:]) * 0.59939338
    else:
        return None

def get_faltantes(cdf, original, target):
    return cdf[cdf[target].isna() & ~(cdf[original].isna())]

df["budget_usd"] = df["budget"].map(parse_money)
get_faltantes(df, "budget", "budget_usd")

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,production_companies,release_date,comentarios_ia,ai_summary,duration_mins,budget,gross_world,gross_usa_canada,opening_weekend_usa_canada,budget_usd
119,Paprika,https://www.imdb.com/title/tt0851578/?ref_=sr_...,81,R,2006,1h 30m,7.7,(107K),When a machine that allows therapists to enter...,[Satoshi Kon],...,"[Madhouse, Sony Pictures Releasing]","June 22, 2007 (United States)",[],,90,"¥300,000,000 (estimated)","$967,432","$882,267","$35,593May 27, 2007",NaN
127,This Is England,https://www.imdb.com/title/tt0480025/?ref_=sr_...,86,Not Rated,2006,1h 41m,7.7,(133K),A young boy becomes friends with a gang of ski...,[Shane Meadows],...,"[Warp Films, Big Arty Productions, EM Media]","April 27, 2007 (United Kingdom)",[],,101,"£1,500,000 (estimated)","$8,481,254","$329,379","$18,430Jul 29, 2007",NaN
130,The Name of the Rose,https://www.imdb.com/title/tt0091605/?ref_=sr_...,54,R,1986,2h 10m,7.7,(124K),An intellectually nonconformist friar investig...,[Jean-Jacques Annaud],...,"[Constantin Film, Cristaldifilm, Les Films Ari...","September 24, 1986 (United States)",[],,130,"ITL 30,000,000,000 (estimated)","$7,153,487","$7,153,487","$494,571Sep 28, 1986",NaN
139,The Last Emperor,https://www.imdb.com/title/tt0093389/?ref_=sr_...,76,PG-13,1987,2h 43m,7.7,(117K),Bernardo Bertolucci's Oscar-winning dramatizat...,[Bernardo Bertolucci],...,"[Yanco Films Limited, TAO Film, Recorded Pictu...","April 15, 1988 (United States)",[],,163,"£23,000,000 (estimated)","$44,043,391","$43,984,230","$149,460Nov 22, 1987",NaN
156,Open Your Eyes,https://www.imdb.com/title/tt0125659/?ref_=sr_...,No Score,R,1997,1h 59m,7.7,(76K),A very handsome man finds the love of his life...,[Alejandro Amenábar],...,"[Sociedad General de Televisión (Sogetel), Las...","December 19, 1997 (Spain)",[],,119,"ESP 370,000,000 (estimated)","$377,967","$370,720","$38,289Apr 18, 1999",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,Seven Samurai,https://www.imdb.com/title/tt0047478/?ref_=sr_...,98,Not Rated,1954,3h 27m,8.6,(391K),Farmers from a village exploited by bandits hi...,[Akira Kurosawa],...,[Toho],"November 19, 1956 (United States)","[Artistic vision positive sentiment, Authentic...",Reviewers say 'Seven Samurai' is highly rated ...,207,"¥125,000,000 (estimated)","$1,092,319","$820,278","$15,942Jul 28, 2002",NaN
972,Soorarai Pottru,https://www.imdb.com/title/tt10189514/?ref_=sr...,No Score,Not Rated,2020,2h 33m,8.6,(130K),A determined villager challenges the aviation ...,[Sudha Kongara],...,"[2D Entertainment, Sikhya Entertainment, Goldm...","November 12, 2020 (United States)",[],,153,"₹150,000,000 (estimated)",None,None,None,NaN
975,Nayakan,https://www.imdb.com/title/tt0093603/?ref_=sr_...,No Score,Not Rated,1987,2h 25m,8.6,(27K),A common man's struggles against a corrupt pol...,[Mani Ratnam],...,"[Muktha Films, Sujatha Film]","October 21, 1987 (India)","[Authentic emotion positive sentiment, Cinemat...",Reviewers say 'Nayakan' is a seminal work in I...,145,"₹10,000,000 (estimated)",None,None,None,NaN
976,Rocketry: The Nambi Effect,https://www.imdb.com/title/tt9263550/?ref_=sr_...,No Score,Not Rated,2022,2h 37m,8.6,(61K),The story of Indian Space Research Organizatio...,[Madhavan],...,"[Tricolour Productions, Varghese Moolan Pictur...","July 1, 2022 (India)",[],,157,"₹600,000,000 (estimated)","$398,615",None,None,NaN
985,Mahavatar Narsimha,https://www.imdb.com/title/tt34365591/?ref_=sr...,No Score,Not Rated,2024,2h 10m,8.8,(39K),The demon Hiranyakashyap seeks revenge on Vish...,[Ashwin Kumar],...,"[Kleem Productions, Hombale Films]","August 1, 2025 (United States)",[],,130,"₹400,000,000 (estimated)","$879,020",None,None,NaN

In [68]:
df["gross_world_usd"] = df["gross_world"].map(parse_money)
get_faltantes(df, "gross_world", "gross_world_usd")

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,release_date,comentarios_ia,ai_summary,duration_mins,budget,gross_world,gross_usa_canada,opening_weekend_usa_canada,budget_usd,gross_world_usd
852,Hera Pheri,https://www.imdb.com/title/tt0242519/?ref_=sr_...,No Score,Not Rated,2000,2h 36m,8.2,(78K),Two tenants and a landlord look for answers to...,[Priyadarshan],...,"March 31, 2000 (India)",[],,156,None,"₹214,000,000",None,None,NaN,NaN
897,Premam,https://www.imdb.com/title/tt4679210/?ref_=sr_...,No Score,Not Rated,2015,2h 36m,8.3,(27K),A young man has three opportunities to find lo...,[Alphonse Puthren],...,"June 12, 2015 (United States)",[],,156,None,"₹600,000,000","$178,000",None,NaN,NaN
899,Raatchasan,https://www.imdb.com/title/tt7060344/?ref_=sr_...,No Score,Not Rated,2018,2h 26m,8.3,(57K),A sub-inspector sets out in pursuit of a myste...,[Ram Kumar],...,"October 5, 2018 (United States)",[],,146,None,"₹200,000,000",None,None,NaN,NaN

In [69]:
df["gross_usa_canada_usd"] = df["gross_usa_canada"].map(parse_money)
get_faltantes(df, "gross_usa_canada", "gross_usa_canada_usd")

Empty DataFrame
Columns: [title, url, metacritic_score, rating, year, duration, rating_stars, voters, description, director, writers, stars, storyline, genres, genres_ext, awards_and_nominations, cast, box_office, aspect_ratio, countries, languages, production_companies, release_date, comentarios_ia, ai_summary, duration_mins, budget, gross_world, gross_usa_canada, opening_weekend_usa_canada, budget_usd, gross_world_usd, gross_usa_canada_usd]
Index: []

[0 rows x 33 columns]

In [70]:
def split_at_date(value: str) -> (str, str):
    idx = 0

    if value is None:
        return (None, None)

    while idx < len(value):
        try:
            if value[idx].isupper() and value[idx-1].isnumeric():
                return value[:idx], value[idx:]
        except IndexError:
            return value[:idx], value[idx:]

        idx += 1

# df["opening_weekend_usa_canada_usd"] = df["opening_weekend_usa_canada"].map(parse_money)
# get_faltantes(df, "opening_weekend_usa_canada", "opening_weekend_usa_canada_usd")

open_info = df["opening_weekend_usa_canada"].map(split_at_date)
df["opening_weekend_usa_canada_date"] = open_info.map(lambda x: x[1])
df["opening_weekend_usa_canada_usd"] = open_info.map(lambda x: parse_money(x[0]))

get_faltantes(df, "opening_weekend_usa_canada", "opening_weekend_usa_canada_usd")

Empty DataFrame
Columns: [title, url, metacritic_score, rating, year, duration, rating_stars, voters, description, director, writers, stars, storyline, genres, genres_ext, awards_and_nominations, cast, box_office, aspect_ratio, countries, languages, production_companies, release_date, comentarios_ia, ai_summary, duration_mins, budget, gross_world, gross_usa_canada, opening_weekend_usa_canada, budget_usd, gross_world_usd, gross_usa_canada_usd, opening_weekend_usa_canada_date, opening_weekend_usa_canada_usd]
Index: []

[0 rows x 35 columns]

In [71]:
df.head()

,title,url,metacritic_score,rating,year,duration,rating_stars,voters,description,director,...,duration_mins,budget,gross_world,gross_usa_canada,opening_weekend_usa_canada,budget_usd,gross_world_usd,gross_usa_canada_usd,opening_weekend_usa_canada_date,opening_weekend_usa_canada_usd
0,Once Upon a Time... in Hollywood,https://www.imdb.com/title/tt7131622/?ref_=sr_t_1,84,R,2019,2h 41m,7.6,(930K),As Hollywood's Golden Age is winding down duri...,[Quentin Tarantino],...,161,"$90,000,000 (estimated)","$392,105,159","$142,502,728","$41,082,018Jul 28, 2019",9.000000e+07,392105159.0,142502728.0,"Jul 28, 2019",41082018.0
1,Mission: Impossible - Dead Reckoning Part One,https://www.imdb.com/title/tt9603212/?ref_=sr_t_2,81,PG-13,2023,2h 43m,7.6,(313K),Ethan Hunt and his IMF team must track down a ...,[Christopher McQuarrie],...,163,"$291,000,000 (estimated)","$571,125,435","$172,640,980","$54,688,347Jul 16, 2023",2.910000e+08,571125435.0,172640980.0,"Jul 16, 2023",54688347.0
2,John Wick: Chapter 4,https://www.imdb.com/title/tt10366206/?ref_=sr...,78,R,2023,2h 49m,7.6,(394K),John Wick uncovers a path to defeating The Hig...,[Chad Stahelski],...,169,"$100,000,000 (estimated)","$447,142,521","$187,131,806","$73,817,950Mar 26, 2023",1.000000e+08,447142521.0,187131806.0,"Mar 26, 2023",73817950.0
3,The Fifth Element,https://www.imdb.com/title/tt0119116/?ref_=sr_t_4,52,PG-13,1997,2h 6m,7.6,(534K),"In the colorful future, cabdriver Korben Dalla...",[Luc Besson],...,126,"FRF 75,210,000 (estimated)","$263,920,180","$63,820,180","$17,031,345May 11, 1997",1.344123e+07,263920180.0,63820180.0,"May 11, 1997",17031345.0
4,Watchmen,https://www.imdb.com/title/tt0409459/?ref_=sr_t_5,56,R,2009,2h 42m,7.6,(604K),"In a version of 1985 where superheroes exist, ...",[Zack Snyder],...,162,"$130,000,000 (estimated)","$185,382,813","$107,509,799","$55,214,334Mar 8, 2009",1.300000e+08,185382813.0,107509799.0,"Mar 8, 2009",55214334.0

In [72]:
def parse_awards(value: str) -> (int, int):
    words = value.split(" ")
    nominations = 0
    awards = 0

    for idx, word in enumerate(words):
        if word.startswith("win"):
            awards = int(words[idx-1])
        elif word.startswith("nomina"):
            nominations = int(words[idx-1])

    return awards, nominations

df["awards"] = df["awards_and_nominations"].map(lambda x: parse_awards(x)[0])
df["nominations"] = df["awards_and_nominations"].map(lambda x: parse_awards(x)[1])

df[["awards_and_nominations", "awards", "nominations"]].head()

             awards_and_nominations  awards  nominations
0  146 wins & 377 nominations total     146          377
1    18 wins & 68 nominations total      18           68
2    38 wins & 51 nominations total      38           51
3    10 wins & 39 nominations total      10           39
4    12 wins & 24 nominations total      12           24

In [73]:
def parse_value(value: str) -> int:
    if 'M' in value:
        return int(float(value[:-1]) * 1_000_000)
    if 'K' in value:
        return int(float(value[:-1]) * 1_000)

df["voters_int"] = df["voters"].replace(r"\(|\)| ", "", regex=True).map(parse_value)

df[["voters", "voters_int"]].head()

    voters  voters_int
0   (930K)      930000
1   (313K)      313000
2   (394K)      394000
3   (534K)      534000
4   (604K)      604000

In [74]:
df["rating_stars_int"] = df["rating_stars"].astype("float")
df[["rating_stars", "rating_stars_int"]].head()

  rating_stars  rating_stars_int
0          7.6               7.6
1          7.6               7.6
2          7.6               7.6
3          7.6               7.6
4          7.6               7.6

In [75]:
def parse_metacritic(value: str) -> int:
    try:
        return int(value)
    except ValueError:
        return None

df["metacritic_score_int"] = df["metacritic_score"].map(parse_metacritic)
df[["metacritic_score", "metacritic_score_int"]].head()

  metacritic_score  metacritic_score_int
0               84                  84.0
1               81                  81.0
2               78                  78.0
3               52                  52.0
4               56                  56.0

In [76]:
df["year_int"] = df["year"].astype("int")

In [80]:
final_df = df.copy()
final_df.drop(columns=[
    "metacritic_score",
    "rating_stars",
    "voters",
    "year",
    "duration",
    "gross_usa_canada",
    "gross_world",
    "budget",
    "opening_weekend_usa_canada",
], inplace=True)

In [81]:
final_df

,title,url,rating,description,director,writers,stars,storyline,genres,genres_ext,...,gross_world_usd,gross_usa_canada_usd,opening_weekend_usa_canada_date,opening_weekend_usa_canada_usd,awards,nominations,voters_int,rating_stars_int,metacritic_score_int,year_int
0,Once Upon a Time... in Hollywood,https://www.imdb.com/title/tt7131622/?ref_=sr_t_1,R,As Hollywood's Golden Age is winding down duri...,[Quentin Tarantino],[Quentin Tarantino],"[Leonardo DiCaprio, Brad Pitt, Margot Robbie]",Quentin Tarantino's Once Upon a Time... in Hol...,"[Comedy, Drama]","[Period Drama, Showbiz Drama, Comedy, Drama]",...,3.921052e+08,142502728.0,"Jul 28, 2019",41082018.0,146,377,930000,7.6,84.0,2019
1,Mission: Impossible - Dead Reckoning Part One,https://www.imdb.com/title/tt9603212/?ref_=sr_t_2,PG-13,Ethan Hunt and his IMF team must track down a ...,[Christopher McQuarrie],"[Bruce Geller, Christopher McQuarrie, Erik Jen...","[Tom Cruise, Hayley Atwell, Ving Rhames]",Ethan Hunt and the IMF team must track down a ...,"[Action, Adventure, Thriller]","[Action Epic, Adventure Epic, Spy, Action, Adv...",...,5.711254e+08,172640980.0,"Jul 16, 2023",54688347.0,18,68,313000,7.6,81.0,2023
2,John Wick: Chapter 4,https://www.imdb.com/title/tt10366206/?ref_=sr...,R,John Wick uncovers a path to defeating The Hig...,[Chad Stahelski],"[Shay Hatten, Michael Finch, Derek Kolstad]","[Keanu Reeves, Laurence Fishburne, George Geor...",Condemned by the tyrannical High Table to be o...,"[Action, Crime, Thriller]","[Action Epic, Gun Fu, One-Person Army Action, ...",...,4.471425e+08,187131806.0,"Mar 26, 2023",73817950.0,38,51,394000,7.6,78.0,2023
3,The Fifth Element,https://www.imdb.com/title/tt0119116/?ref_=sr_t_4,PG-13,"In the colorful future, cabdriver Korben Dalla...",[Luc Besson],"[Luc Besson, Robert Mark Kamen]","[Bruce Willis, Milla Jovovich, Gary Oldman]","In the 23rd century, the universe is threatene...","[Action, Adventure, Sci-Fi]","[Sci-Fi Epic, Space Sci-Fi, Action, Adventure,...",...,2.639202e+08,63820180.0,"May 11, 1997",17031345.0,10,39,534000,7.6,52.0,1997
4,Watchmen,https://www.imdb.com/title/tt0409459/?ref_=sr_t_5,R,"In a version of 1985 where superheroes exist, ...",[Zack Snyder],"[Dave Gibbons, David Hayter, Alex Tse]","[Jackie Earle Haley, Patrick Wilson, Carla Gug...",It's 1985 in an alternate reality. The Watchme...,"[Action, Drama, Mystery, Sci-Fi]","[Dystopian Sci-Fi, Superhero, Action, Drama, M...",...,1.853828e+08,107509799.0,"Mar 8, 2009",55214334.0,12,24,604000,7.6,56.0,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,The Godfather Part II,https://www.imdb.com/title/tt0071562/?ref_=sr_...,R,The early life and career of Vito Corleone in ...,[Francis Ford Coppola],"[Francis Ford Coppola, Mario Puzo]","[Al Pacino, Robert De Niro, Robert Duvall]",The continuing saga of the Corleone crime fami...,"[Crime, Drama]","[Epic, Gangster, Tragedy, Crime, Drama]",...,4.810511e+07,47834595.0,"Nov 10, 2019",171417.0,17,21,1500000,9.0,90.0,1974
996,The Lord of the Rings: The Return of the King,https://www.imdb.com/title/tt0167260/?ref_=sr_...,PG-13,Gandalf and Aragorn lead the World of Men agai...,[Peter Jackson],"[J.R.R. Tolkien, Fran Walsh, Philippa Boyens]","[Elijah Wood, Viggo Mortensen, Ian McKellen]",The final confrontation between the forces of ...,"[Adventure, Drama, Fantasy]","[Action Epic, Adventure Epic, Epic, Fantasy Ep...",...,1.139428e+09,381878219.0,"Dec 21, 2003",72629713.0,215,124,2100000,9.0,94.0,2003
997,The Dark Knight,https://www.imdb.com/title/tt0468569/?ref_=sr_...,PG-13,When a menace known as the Joker wreaks havoc ...,[Christopher Nolan],"[Jonathan Nolan, Christopher Nolan, David S. G...","[Christian Bale, Heath Ledger, Aaron Eckhart]",Set within a year after the events of Batman B...,"[Action, Crime, Drama, Thriller]","[Action Epic, Epic, Psychological Thriller, Su...",...,1.009243e+09,534987076.0,"Jul 20, 2008",158411483.0,163,165,3100000,9.1,85.0,2008
998,The Godfather,https://www.imdb.com/title/tt0068646/?ref_=sr_...,R,The aging patriarch of an organized crime dyna...,[Francis Ford Coppola],"[Mario Puzo, Francis Ford Coppola]","[Marlon Brando, Al Pacino, James Caan]","The Godfather ""Don"" Vito Corleone is the head ...","[Crime, Drama]","[Epic, Gangster, Tragedy, Crime, Drama]",...,2.505954e+08,136381073.0,"Mar 19, 1972",302393.0,31,31,2200000,9.2,100.0,1972
999,The Shawshank Redemption,https://www.imdb.com/title/tt0111161/?ref_=sr_...,R,A banker convicted of uxoricide forms a friend...,[Frank Darabont],"[Stephen King, Frank Darabont]","[Tim Robbins, Morgan Freeman, Bob Gunton]",Chronicles the experiences of a formerly succe...,[Drama],"[Epic, Period Drama, Prison Drama, Drama]",...,2.933403e+07,28767189.0,"Sep 25, 1994",727327.0,21,42,3100000,9.3,82.0,1994

In [82]:
final_df.to_parquet(utils.find_project_root() / "data" / "inter" / "stage2.parquet")